version: "1.0"
info:
  model: int-scaffold
packages:
- name: SiqatestForScaffProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SiqatestForScaffProject
  gitUsername: siqagituser
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.softwareag.com
  wpmRegistry: softwareag
services:
- serviceName: project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:DatabasenewAccount
  packages:
  - name: SiqatestForScaffProject
    version: "1.0"
- serviceName: project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SiqatestForScaffProject
    version: "1.0"
- serviceName: project.siqatestforscaff.integrations:SIQAAdapterFlow
  packages:
  - name: SiqatestForScaffProject
    version: "1.0"
- serviceName: project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:DbAccount
  packages:
  - name: SiqatestForScaffProject
    version: "1.0"
configurationVariables:
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionManagerSettings.poolIncrementSize
  : "1"
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.jdbcTestPool.maxConns: "10"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionSettings.portNumber
  : "1433"
  jdbc.jdbcTestPool.spyenabled: "false"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionManagerSettings.poolable
  : "false"
  jdbc.jdbcTestPool.snoopenabled: "false"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionSettings.databaseName
  : SIQACloud
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionSettings.serverName
  : vmiboint01
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionSettings.user
  : sa
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionManagerSettings.heartBeatInterval
  : "0"
  jdbc.jdbcTestPool.expireTime: "60000"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionSettings.serverName
  : vmiboint01
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionSettings.dbType
  : MSSQL
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionManagerSettings.expireTimeout
  : "1000"
  jdbc.jdbcTestPool.poolThreshold: "0"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionSettings.dbType
  : MSSQL
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionSettings.user
  : sa
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  jdbc.jdbcTestPool.userid: root
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionSettings.password
  : "{AES}B2Xqma4Ost5nVUiXctJydQ=="
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionManagerSettings.minimumPoolSize
  : "0"
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionEnabled
  : "false"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionSettings.portNumber
  : "1433"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionEnabled
  : "false"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionSettings.trustStore
  : ""
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionSettings.keyStore
  : ""
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionManagerSettings.minimumPoolSize
  : "0"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionSettings.password
  : "{AES}B2Xqma4Ost5nVUiXctJydQ=="
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionSettings.keyStore
  : ""
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionSettings.trustStore
  : ""
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DbAccount.connectionManagerSettings.maximumPoolSize
  : "10"
  jdbc.jdbcTestPool.useSSL: "false"
  ? artConnection.SiqatestForScaffProject.project.siqatestforscaff.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAccount.connectionManagerSettings.expireTimeout
  : "1000"
